name: URL Monitoring

on:
  schedule:
    - cron: "* * * * *"  # every 1 minute
  workflow_dispatch:     # allow manual run

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create monitoring directory
        run: mkdir -p ./monitoring

      - name: Download previous results (if exist)
        uses: dawidd6/action-download-artifact@v3
        with:
          name: url-monitor-results
          path: ./monitoring
          if_no_artifact_found: ignore

      - name: Copy monitor script to monitoring dir
        run: cp ./monitor_urls.sh ./monitoring/

      - name: Make script executable
        run: chmod +x ./monitoring/monitor_urls.sh

      - name: Run URL monitor (2 checks at 20s intervals)
        run: ./monitor_urls.sh --interval 20s --maxrequests 2 --urls https://aem-s6web-preprod-skyplus6e.goindigo.in/content/dam/s6common/in/en/assets/homepage/videos/new_videos/app/Seychelles-224.mp4 https://aem-s6web-preprod-skyplus6e.goindigo.in/content/dam/s6common/in/en/assets/homepage/videos/new_videos/app/Mauritius-updated.mp4 https://aem-s6web-preprod-skyplus6e.goindigo.in/content/dam/s6common/in/en/assets/homepage/videos/new_videos/app/Kenya-updated.mp4 https://preprod.goindigo.in/content/dam/s6common/in/en/assets/homepage/videos/new_videos/app/Delhi_app.mp4 https://preprod.goindigo.in/content/dam/s6common/in/en/assets/homepage/videos/new_videos/app/Goa_app.mp4 https://www.goindigo.in/content/dam/s6common/in/en/assets/homepage/videos/new_videos/app/Mumbai_app.mp4
        working-directory: ./monitoring

      - name: Upload updated consolidated CSV
        uses: actions/upload-artifact@v4
        with:
          name: url-monitor-results
          path: ./monitoring/url_monitoring_results.csv
