name: URL Monitoring

on:
  schedule:
    - cron: "* * * * *"  # every 1 minute
  workflow_dispatch:     # allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create monitoring directory
        run: mkdir -p ./monitoring

      - name: Download previous results (if exist)
        uses: dawidd6/action-download-artifact@v3
        with:
          name: url-monitor-results
          path: ./monitoring
          if_no_artifact_found: ignore

      - name: Make monitor script executable
        run: chmod +x ./monitor_urls.sh

      - name: Run URL monitor (6 times at 10s intervals)
        run: ./monitor_urls.sh --interval 10s --maxrequests 6 --urls https://example.com/video1.mp4 https://example.com/video2.mp4
        working-directory: ./monitoring

      - name: Upload updated consolidated CSV
        uses: actions/upload-artifact@v4
        with:
          name: url-monitor-results
          path: ./monitoring/url_monitoring_results.csv
